services:
  - type: web
    name: fittag
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
      - key: OMP_NUM_THREADS
        value: 1
      - key: OPENBLAS_NUM_THREADS
        value: 1
