"""Build public PWA assets from synthetic data; never personal garment sizes."""
import shutil
from pathlib import Path
from PIL import Image, ImageDraw
ROOT = Path(__file__).resolve().parent.parent

def main():
    web = ROOT / "web"
    shutil.copy2(web / "free.html", web / "index.html")
    # Checked-in demo assets are generated by tools.make_phone_example.
    # Building the shell never reintroduces a personal garment sample.
    for name in ("demo.json", "demo.jpg", "example-photo.jpg"):
        if not (web / name).is_file():
            raise FileNotFoundError(f"Missing {name}; run python -m tools.make_phone_example")
    for size in (192,512):
        img = Image.new("RGB",(512,512),"#fbf8f2"); d=ImageDraw.Draw(img)
        d.polygon([(145,100),(315,100),(375,160),(375,412),(145,412)],fill="#b53322")
        d.ellipse((310,143,338,171),fill="#fbf8f2")
        d.line([(198,354),(198,222),(316,222)],fill="#fbf8f2",width=24)
        d.line([(198,280),(287,280)],fill="#fbf8f2",width=24)
        img.resize((size,size),Image.Resampling.LANCZOS).save(web / f"icons/icon-{size}.png")
    for name in ("index.html","button.html","free.html","free.css","free.js","free.mjs","request.mjs","photo-check.mjs","batch.mjs","camera.mjs","studio.css","example-jeans.jpg","free-demo.json","free-demo.jpg","app.css","app.js","client.mjs","sw.js","manifest.webmanifest","demo.json","demo.jpg","example-photo.jpg"):
        shutil.copy2(web / name, ROOT / "docs" / name)
    shutil.copytree(web / "icons", ROOT / "docs/icons", dirs_exist_ok=True)
    (ROOT / "docs/.nojekyll").touch()

if __name__ == "__main__":
    main()
