import {labels,validateFile,formatValue} from './client.mjs';
import {anchorResult,rowText,resultMessage,moveEndpoint,listingText} from './free.mjs';
const $=id=>document.getElementById(id);
let file=null,second=null,previewURL=null,current=null,baseResult=null,geometry=null,drag=null,unit='cm',active=null,run=0,controller=null,installPrompt=null,backend=null;
const timerController=new AbortController(),healthTimeout=setTimeout(()=>timerController.abort(),10000);
fetch('./experiment',{signal:timerController.signal}).then(r=>{backend=r.ok;if(!r.ok)$('modeNotice').hidden=false;}).catch(()=>{}).finally(()=>clearTimeout(healthTimeout));
function show(name){for(const id of ['capture','processing','results'])$(id).hidden=id!==name;$('error').hidden=true;}
function error(message){$('errorText').textContent=message;$('error').hidden=false;$('error').focus();}
function selected(next){const problem=validateFile(next);if(problem)return error(problem);if(previewURL)URL.revokeObjectURL(previewURL);file=next;previewURL=URL.createObjectURL(file);$('preview').src=previewURL;$('preview').hidden=false;$('illustration').hidden=true;$('selectedLabel').hidden=false;$('capture').classList.add('has-photo');$('viewfinder').removeAttribute('role');$('viewfinder').removeAttribute('tabindex');$('captureTitle').textContent='Every edge visible? Read the photo.';$('measure').hidden=$('clear').hidden=false;$('take').textContent='Change photo';$('choose').textContent='Change photo';$('viewfinder').scrollIntoView({block:'start'});$('measure').focus({preventScroll:true});}
function clear(){if(previewURL)URL.revokeObjectURL(previewURL);file=null;previewURL=null;$('preview').removeAttribute('src');$('preview').hidden=true;$('illustration').hidden=false;$('selectedLabel').hidden=true;$('capture').classList.remove('has-photo');$('viewfinder').setAttribute('role','button');$('viewfinder').tabIndex=0;$('captureTitle').textContent='Flat garment. Clear floor. Straight down.';$('measure').hidden=$('clear').hidden=true;$('camera').value=$('upload').value='';$('take').textContent='Take photo';$('choose').textContent='Choose photo';clearSecond();}
function clearSecond(){second=null;$('secondFile').value='';$('secondStatus').textContent='Optional. Both photos upload only when you tap Read photo.';$('secondClear').hidden=true;}
$('take').onclick=()=>$('camera').click();$('choose').onclick=()=>$('upload').click();for(const id of ['camera','upload'])$(id).onchange=e=>{if(e.target.files[0])selected(e.target.files[0]);};$('clear').onclick=clear;
$('secondChoose').onclick=()=>$('secondFile').click();$('secondClear').onclick=clearSecond;$('secondFile').onchange=e=>{const candidate=e.target.files[0];if(!candidate)return;const problem=validateFile(candidate);if(problem)return error(problem);second=candidate;$('secondStatus').textContent='Second photo ready. Confirm it shows this same garment, laid out the same way.';$('secondClear').hidden=false;};
$('method').onchange=()=>{$('distanceOptions').hidden=$('method').value!=='distance';$('secondOptions').hidden=$('method').value!=='depth';};
$('customFov').onchange=()=>$('fov').disabled=!$('customFov').checked;
$('kind').onchange=()=>{$('jeansDrawing').hidden=$('kind').value!=='jeans';$('topDrawing').hidden=$('kind').value==='jeans';$('layoutGuide').textContent=$('kind').value==='jeans'?'Waistband at the top. Separate the legs and include both hems.':'Neckline at the top. Spread both sleeves and include the full hem.';};
$('measure').onclick=async()=>{
 if(backend===false)return error('This is a static preview. Open the full experimental service; your photo has not been uploaded.');
 if(!navigator.onLine)return error('Connect to read a new photo. Nothing has been uploaded.');
 if(!file)return error('Choose a photo first.');
 if($('method').value==='distance'&&(!$('cameraHeight').value||!$('cameraHeight').checkValidity()))return error('Enter a known lens-to-floor distance between 35 and 350 cm.');
 if(file.size+($('method').value==='depth'&&second?second.size:0)>12*1024*1024)return error('The combined photos must be smaller than 12 MB.');
 if($('customFov').checked&&!$('fov').checkValidity())return error('Enter a diagonal field of view between 40 and 110 degrees.');
 const token=++run,request=new AbortController();controller=request;const timeout=setTimeout(()=>request.abort(),120000);
 const body=new FormData();body.append('file',file);body.append('garment_type',$('kind').value);body.append('fov_deg',$('customFov').checked?$('fov').value:'0');body.append('estimate',String($('method').value==='depth'));body.append('camera_height_cm',$('method').value==='distance'?$('cameraHeight').value:'0');if(second&&$('method').value==='depth')body.append('second',second);
 show('processing');$('processingTitle').textContent=$('method').value==='shape'?'Tracing the outline.':$('method').value==='distance'?'Applying your distance.':'Reading the floor.';$('progressText').textContent=$('method').value==='shape'?'Silhouette → garment landmarks → relative proportions':second?'Reading two photos and testing whether scale agrees…':$('method').value==='distance'?'Known height + focal length → near-overhead geometry':'Outline → learned depth → floor plane → landmarks';$('processingTitle').focus();
 try{const response=await fetch('./measure-free',{method:'POST',body,signal:request.signal});const data=await response.json().catch(()=>{throw Error('The server may be waking up. Try again shortly.');});if(!response.ok||!data.ok)throw Error(typeof data.detail==='string'?data.detail:data.error||'This image could not be analysed.');if(token===run)render(data);}
 catch(e){if(token===run){show('capture');error(e.name==='AbortError'?'The request timed out. Your photo is still selected.':e.message);}}
 finally{clearTimeout(timeout);if(token===run)controller=null;}
};
$('cancel').onclick=()=>{++run;controller?.abort();controller=null;show('capture');$('measure').focus();};$('again').onclick=()=>{show('capture');clear();$('take').focus();};
function table(){
 $('measurements').replaceChildren();$('units').hidden=current.mode==='shape';$('tableTitle').textContent=current.mode==='shape'?'Proportions':current.mode==='anchored'?'Anchored measurements':current.mode==='distance'?'Distance estimates':'Model guesses';$('ratioBasis').textContent=current.mode==='shape'?`${current.garment_type==='jeans'?'Inseam':'Garment length'} = 100%. These are ratios, not centimetres.`:'';
 for(const row of current.rows){const tr=document.createElement('tr'),th=document.createElement('th'),td=document.createElement('td'),button=document.createElement('button');th.scope='row';button.className='measurement-link';button.textContent=labels[row.name]||row.name;button.setAttribute('aria-pressed',String(active===row.name));button.onclick=e=>{active=active===row.name?null:row.name;table();lines();if(e.detail>0&&matchMedia('(max-width:680px)').matches)$('overlay').scrollIntoView({block:'center',behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth'});};th.append(button);td.textContent=rowText(row,unit);if(row.tolerance_cm!==undefined){const small=document.createElement('small');small.textContent=` ±${formatValue(row.tolerance_cm,unit)} ${unit}`;td.append(small);}tr.append(th,td);$('measurements').append(tr);}
}
function lines(){const focusEndpoint=document.activeElement?.getAttribute('data-endpoint');const svg=$('lines');svg.removeAttribute('aria-hidden');svg.setAttribute('role','group');svg.setAttribute('aria-label','Garment measurement lines');$('editHint').hidden=!active;svg.replaceChildren();const [w,h]=current.image_size;svg.setAttribute('viewBox',`0 0 ${w} ${h}`);const make=(tag,attrs)=>{const el=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const [key,value]of Object.entries(attrs))el.setAttribute(key,value);return el;};for(const row of current.rows){const color=active===row.name?'#fffefa':'#e3be4b',g=make('g',{opacity:active&&active!==row.name?'.22':'1'});g.append(make('line',{x1:row.p1[0],y1:row.p1[1],x2:row.p2[0],y2:row.p2[1],stroke:color,'stroke-width':active===row.name?'3':'2','vector-effect':'non-scaling-stroke'}));const hit=make('line',{x1:row.p1[0],y1:row.p1[1],x2:row.p2[0],y2:row.p2[1],stroke:'transparent','stroke-width':'24','vector-effect':'non-scaling-stroke','pointer-events':'stroke'});hit.onclick=()=>{active=active===row.name?null:row.name;table();lines();};g.append(hit);for(const [index,p]of [row.p1,row.p2].entries()){const dot=make('circle',{cx:p[0],cy:p[1],r:Math.max(w,h)*.006,fill:color});g.append(dot);if(active===row.name){const handle=make('circle',{cx:p[0],cy:p[1],r:24*w/(svg.getBoundingClientRect?.().width||Math.max(w,h)*.4),fill:'transparent',class:'endpoint','data-endpoint':index===0?'p1':'p2',tabindex:'0',role:'button','aria-label':`${index===0?'Start':'End'} of ${labels[row.name]||row.name}; arrow keys adjust`,'pointer-events':'all'});handle.onkeydown=e=>{const steps={ArrowLeft:[-5,0],ArrowRight:[5,0],ArrowUp:[0,-5],ArrowDown:[0,5]},delta=steps[e.key];if(delta){e.preventDefault();correct(row.name,index===0?'p1':'p2',[p[0]+delta[0],p[1]+delta[1]],geometry);}};g.append(handle);}}svg.append(g);}if(focusEndpoint)svg.querySelector(`[data-endpoint="${focusEndpoint}"]`)?.focus?.({preventScroll:true});const row=current.rows.find(r=>r.name===active);$('overlayCaption').textContent=row?`${labels[row.name]||row.name} · ${rowText(row,unit)}`:current.demo?'Simulated garment · actual model run':'Tap a measurement to inspect its line.';}
function update(){table();lines();$('confidence').textContent=resultMessage(current);$('confirm').checked=false;$('save').disabled=true;$('saveStatus').textContent='';}
function render(data){$('itemName').value='';$('copyStatus').textContent='';$('demoTruth').hidden=!data.demo;$('demoTruth').textContent=data.demo?`Counterexample: known simulated waist ${(data.demo_truth_cm?.waist_flat||41).toFixed(1)} cm; model guess ${data.rows.find(r=>r.name==='waist_flat')?.value_cm?.toFixed(1)||'withheld'} cm. Floor consistency did not establish accuracy.`:'';baseResult=data;geometry=structuredClone(data);current=geometry;active=null;show('results');$('resultTitle').textContent=data.mode==='shape'?'Shape recovered':'Check the outline';$('resultTitle').focus();$('resultMode').textContent=data.demo?'Simulated example':'Your garment';$('overlay').src=data.overlay_url;$('anchorPoint').replaceChildren();for(const row of data.rows){const option=document.createElement('option');option.value=row.name;option.textContent=labels[row.name]||row.name;$('anchorPoint').append(option);}$('anchorCm').value='';$('anchorStatus').textContent='';$('anchorReset').hidden=true;$('notes').replaceChildren();for(const note of data.notes){const li=document.createElement('li');li.textContent=note;$('notes').append(li);}$('diagnostics').replaceChildren();const names={focal_source:'Camera focal length',diagonal_fov_deg:'Diagonal field of view',floor_depth_m:'Inferred floor depth (m)',camera_height_cm:'Supplied camera height (cm)',plane_residual_pct:'Floor median residual (%)',plane_p90_pct:'Floor 90th percentile residual (%)',tilt_deg:'Inferred floor tilt (°)',processing_seconds:'Processing time (s)'};for(const [key,label]of Object.entries(names)){if(data.diagnostics[key]===undefined)continue;const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=String(data.diagnostics[key]);$('diagnostics').append(dt,dd);}$('crossCheck').hidden=!data.cross_check;if(data.cross_check)$('crossCheck').textContent=`Two-photo check: ${data.cross_check.difference_pct}% difference. ${data.cross_check.agreed?'Consistent, but shared model bias remains.':'Scale withheld.'}`;update();}
$('anchorApply').onclick=()=>{try{current=anchorResult(geometry,$('anchorPoint').value,parseFloat($('anchorCm').value));update();$('anchorStatus').textContent='Scale set from your supplied length. The ±20% allowance is an unvalidated guardrail for remaining geometry errors.';$('anchorReset').hidden=false;}catch(e){$('anchorStatus').textContent=e.message;}};
$('anchorReset').onclick=()=>{current=geometry;update();$('anchorStatus').textContent='Supplied scale removed.';$('anchorReset').hidden=true;};
$('confirm').onchange=()=>$('save').disabled=!$('confirm').checked;for(const [id,value]of [['cm','cm'],['inches','in']])$(id).onclick=()=>{unit=value;$('cm').setAttribute('aria-pressed',String(unit==='cm'));$('inches').setAttribute('aria-pressed',String(unit==='in'));table();lines();};
$('demo').onclick=async()=>{try{const response=await fetch('./free-demo.json');if(!response.ok)throw Error();render(await response.json());}catch{error('The model example is unavailable. Reconnect to load it.');}};
function saved(){try{const data=JSON.parse(localStorage.getItem('fittag-lab-saved')||'[]');return Array.isArray(data)?data.filter(item=>item&&Array.isArray(item.rows)).slice(0,20):[];}catch{return [];}}
function savedList(){const list=$('savedList');list.replaceChildren();for(const item of saved()){const div=document.createElement('div');div.className='saved-item';div.textContent=`${item.name|| (item.demo?'Example garment':'Saved garment')} · ${new Date(item.date).toLocaleDateString()}`;const p=document.createElement('p');p.textContent=item.rows.map(row=>`${labels[row.name]||row.name}: ${rowText(row)}`).join(' / ');div.append(p);list.append(div);}if(!list.childNodes.length){const p=document.createElement('p');p.className='small';p.textContent='No saved clothes yet. Save a measurement sheet to keep it here.';list.append(p);}}
$('save').onclick=()=>{if(!$('confirm').checked)return;try{localStorage.setItem('fittag-lab-saved',JSON.stringify([{name:$('itemName').value.trim().slice(0,80),date:new Date().toISOString(),mode:current.mode,demo:!!current.demo,rows:current.rows,anchor:current.anchor||null,edited:!!current.edited},...saved()].slice(0,20)));$('saveStatus').textContent='Readout saved locally. Photos are not saved.';$('save').disabled=true;savedList();}catch{$('saveStatus').textContent='Device storage is unavailable. Your result remains visible.';}};
$('forget').onclick=()=>{try{localStorage.removeItem('fittag-lab-saved');savedList();}catch{error('Device storage is unavailable.');}};
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;$('nativeInstall').hidden=false;});$('install').onclick=()=>$('installDialog').showModal();$('closeInstall').onclick=()=>$('installDialog').close();$('nativeInstall').onclick=async()=>{if(installPrompt){await installPrompt.prompt();installPrompt=null;$('nativeInstall').hidden=true;$('installDialog').close();}};
function network(){$('network').hidden=navigator.onLine;}window.addEventListener('online',network);window.addEventListener('offline',network);network();savedList();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});

function correct(name,endpoint,point,source){
 try{const anchor=current.anchor;geometry=moveEndpoint(source,name,endpoint,point);current=anchor?anchorResult(geometry,anchor.name,anchor.cm):geometry;update();$('anchorStatus').textContent='Line corrected. Scale assumptions still apply.';}
 catch{ /* A coincident endpoint is rejected; preserve the last usable line. */ }
}
$('lines').onpointerdown=e=>{const endpoint=e.target.getAttribute('data-endpoint');if(!endpoint||!active)return;e.preventDefault();drag={name:active,endpoint,source:structuredClone(geometry)};$('lines').setPointerCapture(e.pointerId);};
$('lines').onpointermove=e=>{if(!drag)return;const box=$('lines').getBoundingClientRect(),[w,h]=current.image_size;const p=[(e.clientX-box.left)*w/box.width,(e.clientY-box.top)*h/box.height];correct(drag.name,drag.endpoint,p,drag.source);const zoom=box.width/w*2.5;$('magnifier').hidden=false;$('magnifier').style.backgroundImage=`url(${JSON.stringify(current.overlay_url)})`;$('magnifier').style.backgroundSize=`${w*zoom}px ${h*zoom}px`;$('magnifier').style.backgroundPosition=`${45-p[0]*zoom}px ${45-p[1]*zoom}px`;};
$('lines').onpointerup=$('lines').onpointercancel=()=>{drag=null;$('magnifier').hidden=true;};
$('undoEdits').onclick=()=>{const anchor=current.anchor;geometry=structuredClone(baseResult);current=anchor?anchorResult(geometry,anchor.name,anchor.cm):geometry;update();$('anchorStatus').textContent='Original detected lines restored.';};

$('copyListing').onclick=async()=>{
 const text=listingText(current);
 try{await navigator.clipboard.writeText(text);$('copyStatus').textContent='Copied with the scale limitations included.';}
 catch{$('copyStatus').textContent='Clipboard unavailable in this browser. Save the readout locally instead.';}
};

$('viewfinder').onclick=()=>{if(!file)$('upload').click();};
$('viewfinder').onkeydown=e=>{if(!file&&['Enter',' '].includes(e.key)){e.preventDefault();$('upload').click();}};
$('openSaved').onclick=()=>{$('savedSection').open=true;$('savedSection').scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth'});};
